
import React from 'react';
import ProductList from './productList';

const cavalos = [
  {
    id: 1,
    name: 'Mustang',
    href: 'https://blog.7mboots.com.br/wp-content/uploads/2020/06/the-black-horse-of-the-frisian-breed-walks-in-the-P77UURU_Easy-Resize.com_.jpg',
    imageSrc: 'https://blog.7mboots.com.br/wp-content/uploads/2020/06/the-black-horse-of-the-frisian-breed-walks-in-the-P77UURU_Easy-Resize.com_.jpg',
    imageAlt: 'Mustang Horse',
    price: 'R$25.000',
    color: 'Preto',
    breed: 'Mustang',
    description: 'Cavalo Mustang com excelente temperamento e resistência.',
  },
  {
    id: 2,
    name: 'Arabian',
    href: 'https://cptstatic.s3.amazonaws.com/imagens/enviadas/materias/materia26214/cavalo-andando-2-cdc.jpg',
    imageSrc: 'https://cptstatic.s3.amazonaws.com/imagens/enviadas/materias/materia26214/cavalo-andando-2-cdc.jpg',
    imageAlt: 'Arabian Horse',
    price: 'R$35.000',
    color: 'Marrom',
    breed: 'Árabe',
    description: 'Cavalo Árabe, conhecido por sua beleza e agilidade.',
  },
  {
    id: 3,
    name: 'Thoroughbred',
    href: 'https://files.agro20.com.br/uploads/2019/03/mustang-1024x576.jpg',
    imageSrc: 'https://files.agro20.com.br/uploads/2019/03/mustang-1024x576.jpg',
    imageAlt: 'Thoroughbred Horse',
    price: 'R$50.000',
    color: 'Preto',
    breed: 'Puro Sangue',
    description: 'Cavalo de corrida Thoroughbred com pedigree de campeões.',
  },
  {
    id: 4,
    name: 'Appaloosa',
    href: 'https://forbes.com.br/wp-content/uploads/2022/04/agro-cavalos-equinos-14abr22-Lucas-Ninno-getty-1024x683.jpg',
    imageSrc: 'https://forbes.com.br/wp-content/uploads/2022/04/agro-cavalos-equinos-14abr22-Lucas-Ninno-getty-1024x683.jpg',
    imageAlt: 'Appaloosa Horse',
    price: 'R$20.000',
    color: 'Malhado',
    breed: 'Appaloosa',
    description: 'Cavalo Appaloosa com pelagem distinta e ótimo para montaria.',
  },
  {
    id: 5,
    name: 'Quarter Horse',
    href: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8cQEhMUFj7b4Msgj6TZW7msIrnHrEz4R8-Q&s',
    imageSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8cQEhMUFj7b4Msgj6TZW7msIrnHrEz4R8-Q&s',
    imageAlt: 'Quarter Horse',
    price: 'R$30.000',
    color: 'Bay',
    breed: 'Quarter Horse',
    description: 'Cavalo Quarter Horse, ideal para competições de velocidade.',
  },
  {
    id: 6,
    name: 'Friesian',
    href: 'https://diariodonordeste.verdesmares.com.br/image/contentid/policy:1.3569159:1728581836/WhatsApp%20Image%202024-10-10%20at%2012.57.36.jpeg?f=16x9&h=574&w=1020&$p$f$h$w=607cedb',
    imageSrc: 'https://diariodonordeste.verdesmares.com.br/image/contentid/policy:1.3569159:1728581836/WhatsApp%20Image%202024-10-10%20at%2012.57.36.jpeg?f=16x9&h=574&w=1020&$p$f$h$w=607cedb',
    imageAlt: 'Friesian Horse',
    price: 'R$70.000',
    color: 'Preto',
    breed: 'Frísio',
    description: 'Cavalo Frísio elegante e forte, ótimo para dressage.',
  },
  {
    id: 7,
    name: 'Shire',
    href: 'https://i0.wp.com/blog.vaquera.com.br/wp-content/uploads/2021/04/banner_blog_raca_cavalos.png?fit=750%2C560&ssl=1',
    imageSrc: 'https://i0.wp.com/blog.vaquera.com.br/wp-content/uploads/2021/04/banner_blog_raca_cavalos.png?fit=750%2C560&ssl=1',
    imageAlt: 'Shire Horse',
    price: 'R$60.000',
    color: 'Bay',
    breed: 'Shire',
    description: 'Cavalo Shire, um dos maiores e mais poderosos.',
  },
  {
    id: 8,
    name: 'Andalusian',
    href: 'https://s2-g1.glbimg.com/k91_a2JZ_bCFsqNAUNp2zA1wbzA=/0x0:800x449/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2024/0/B/onzAmsS963kpNl5crHsw/thumbnail-image001.png',
    imageSrc: 'https://s2-g1.glbimg.com/k91_a2JZ_bCFsqNAUNp2zA1wbzA=/0x0:800x449/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2024/0/B/onzAmsS963kpNl5crHsw/thumbnail-image001.png',
    imageAlt: 'Andalusian Horse',
    price: 'R$45.000',
    color: 'Cinza',
    breed: 'Andaluz',
    description: 'Cavalo Andaluz com grande presença e habilidade.',
  },
  {
    id: 9,
    name: 'Clydesdale',
    href: 'https://i.pinimg.com/736x/93/8f/e5/938fe53895610e22d5100d42ff0c89b6.jpg',
    imageSrc: 'https://i.pinimg.com/736x/93/8f/e5/938fe53895610e22d5100d42ff0c89b6.jpg',
    imageAlt: 'Clydesdale Horse',
    price: 'R$50.000',
    color: 'Castanho',
    breed: 'Clydesdale',
    description: 'Cavalo Clydesdale, famoso por sua força e aparência.',
  },
  {
    id: 10,
    name: 'Morgan',
    href: 'https://socientifica.com.br/wp-content/uploads/2022/01/cavalo-scaled.jpg',
    imageSrc: 'https://socientifica.com.br/wp-content/uploads/2022/01/cavalo-scaled.jpg',
    imageAlt: 'Morgan Horse',
    price: 'R$30.000',
    color: 'Castanho',
    breed: 'Morgan',
    description: 'Cavalo Morgan, versátil e ótimo para família.',
  },
  {
    id: 11,
    name: 'Paint Horse',
    href: 'https://www.fazendadaroseta.com.br/wp-content/uploads/2020/11/qual-o-cavalo-mais-caro-do-mundo-1-arabe.jpg',
    imageSrc: 'https://www.fazendadaroseta.com.br/wp-content/uploads/2020/11/qual-o-cavalo-mais-caro-do-mundo-1-arabe.jpg',
    imageAlt: 'Paint Horse',
    price: 'R$28.000',
    color: 'Pinto',
    breed: 'Paint',
    description: 'Cavalo Paint Horse, conhecido por sua pelagem colorida.',
  },
  {
    id: 12,
    name: 'Lipizzaner',
    href: 'https://www.petz.com.br/blog/wp-content/uploads/2023/07/o-que-e-um-cavalo-puro-sangue.jpg',
    imageSrc: 'https://www.petz.com.br/blog/wp-content/uploads/2023/07/o-que-e-um-cavalo-puro-sangue.jpg',
    imageAlt: 'Lipizzaner Horse',
    price: 'R$60.000',
    color: 'Branco',
    breed: 'Lipizzaner',
    description: 'Cavalo Lipizzaner, famoso em competições de alta escola.',
  },
  {
    id: 13,
    name: 'Tennessee Walker',
    href: 'https://andrecintra.vet.br/wp-content/uploads/2016/08/Fig.-10.0.jpg',
    imageSrc: 'https://andrecintra.vet.br/wp-content/uploads/2016/08/Fig.-10.0.jpg',
    imageAlt: 'Tennessee Walker Horse',
    price: 'R$25.000',
    color: 'Preto',
    breed: 'Tennessee Walker',
    description: 'Cavalo Tennessee Walker, conhecido por sua marcha suave.',
  },
  {
    id: 14,
    name: 'Percheron',
    href: 'https://diariodonordeste.verdesmares.com.br/image/contentid/policy:1.3569159:1728581836/WhatsApp%20Image%202024-10-10%20at%2012.57.36.jpeg?f=16x9&h=574&w=1020&$p$f$h$w=607cedb',
    imageSrc: 'https://diariodonordeste.verdesmares.com.br/image/contentid/policy:1.3569159:1728581836/WhatsApp%20Image%202024-10-10%20at%2012.57.36.jpeg?f=16x9&h=574&w=1020&$p$f$h$w=607cedb',
    imageAlt: 'Percheron Horse',
    price: 'R$50.000',
    color: 'Cinza',
    breed: 'Percheron',
    description: 'Cavalo Percheron, forte e ideal para trabalho pesado.',
  },
  {
    id: 15,
    name: 'Belgian',
    href: 'https://kinghorse.com.br/wp-content/uploads/2018/09/racas-de-cavalos-do-mundo.jpg',
    imageSrc: 'https://kinghorse.com.br/wp-content/uploads/2018/09/racas-de-cavalos-do-mundo.jpg',
    imageAlt: 'Belgian Horse',
    price: 'R$40.000',
    color: 'Castanho',
    breed: 'Belga',
    description: 'Cavalo Belga, grande e musculoso, ótimo para agricultura.',
  },
  {
    id: 16,
    name: 'Gypsy Vanner',
    href: 'https://blog.mfleiloes.com.br/wp-content/uploads/2022/03/cavalo-pant-horse-1080x620.jpg',
    imageSrc: 'https://blog.mfleiloes.com.br/wp-content/uploads/2022/03/cavalo-pant-horse-1080x620.jpg',
    imageAlt: 'Gypsy Vanner Horse',
    price: 'R$55.000',
    color: 'Malhado',
    breed: 'Gypsy Vanner',
    description: 'Cavalo Gypsy Vanner, conhecido por sua beleza e graça.',
  },
];

  

export default function CavaloList() {
  return <ProductList products={cavalos} title="Cavalos" />;
}